### ISSUE TITLE
How to build?

### ISSUE THREAD

**Issue by yurikoles** [programmerjake/vulkan-cpu#1]
I'm stuck at 
```
CMake Error at CMakeLists.txt:28 (message):
  compiler is not clang
```
I had tried setting `CC=clang` in front of `cmake` and `-DCC=cmake` in back.

**Comment by programmerjake** [comment]
These are the commands I used to setup a working build in an Ubuntu 16.04 chroot, these commands should work on any Ubuntu 16.04 system and will probably work on any Debian derivative that's recent enough if you change the repository names from xenial.
I am not using the version of LLVM that comes with Ubuntu because the CMake paths are messed up in it's config files.
Here's the build commands:

    sudo apt install software-properties-common wget
    wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
    sudo apt-add-repository 'deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial main'
    sudo apt-add-repository 'deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-4.0 main'
    sudo apt update
    sudo apt install build-essential git clang-4.0 llvm-4.0-dev cmake zlib1g-dev
    git clone https://github.com/programmerjake/vulkan-cpu.git
    cd vulkan-cpu
    mkdir build
    cd build
    cmake .. -DCMAKE_CXX_COMPILER="`which clang++-4.0`" -DCMAKE_C_COMPILER="`which clang-4.0`" -DCMAKE_BUILD_TYPE=Debug
    make

**Comment by yurikoles** [comment]
@programmerjake thanks.

**Comment by yurikoles** [comment]
Could you please describe this in README?

**Comment by programmerjake** [comment]
Ubuntu 16.04 just added LLVM 4.0 to the xenial-updates repository, so it now works without needing to add the llvm.org repositories
